image:
  repository: stakkato95/twitter-service-tweets
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  http:
    name: http
    port: 80

ingress:
  enabled: true
